[workspace]
resolver = "2"
members = ["configuration", "remote-files"]

[workspace.dependencies]
indoc = "2.0.5"
opendal = "0.50.0"
rstest = "0.23.0"
schemars = "1.0.0-alpha.15"
serde = "1.0.210"
serde_json = "1.0.128"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = "symbols"
