[package]
name = "remote-files"
version = "0.1.0"
edition = "2021"

[package.metadata.release]
pre-release-commit-message = "'remote-files' tagged to version '{{version}}'"
tag-message = "'remote-files' tag '{{version}}'"
pre-release-replacements = [
  { file = "README.md", search = "\\/remote-files\\/[a-z0-9\\.-]+\\/", replace = "/remote-files/{{version}}/" },
  { file = "schemas/configuration.schema.json", search = "\\/remote-files\\/[a-z0-9\\.-]+\\/", replace = "/remote-files/{{version}}/" }
]

[lib]
name = "rf"
path = "src/lib.rs"

[[bin]]
name = "rf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
colored = "2.0.4"
dirs = "5.0.1"
futures = "0.3.29"
opendal = { version = "0.42.0", default-features = false, features = ["services-gcs", "services-s3", "native-tls"] }
prettytable = "0.10.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
thiserror = "1.0.50"
tokio = { version = "1.35.0", features = ["fs", "io-util", "macros", "rt-multi-thread"] }

[dev-dependencies]
tokio = { version = "1.35.0", features = ["macros", "rt", "rt-multi-thread"] }
url = "2.5.0"
urlencoding = "2.1.3"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
