name: push main / pr main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "schemas/**"
      - "src/**"
      - "tests/**"

jobs:
  checks:
    needs: []
    uses: amountainram/remote-files/.github/workflows/checks.yml@main

  tests:
    needs:
      - checks
    uses: amountainram/remote-files/.github/workflows/tests.yml@main
    secrets:
      configuration_base64: ${{ secrets.CONFIGURATION_TEST_BASE64 }}
      application_default_credentials_base64: ${{ secrets.APPLICATION_DEFAULT_CREDENTIALS_BASE64 }}


  build-application:
    needs: []
    strategy:
      fail-fast: false
      matrix:
        distro: [alpine, bookworm]
        rust-version: ['1.81']
    uses: amountainram/remote-files/.github/workflows/build.yml@main
    with:
      distro: ${{ matrix.distro }}
      rust-version: ${{ matrix.rust-version }}
