name: tests

on:
  workflow_call:
    inputs:
      rust-version:
        default: '1.81'
        required: false
        type: string
    secrets:
      configuration_base64:
        required: true
      application_default_credentials_base64:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: rust:${{ inputs.rust-version }}-bookworm

    steps:
      - uses: actions/checkout@v3
      
      - name: Retrieve taget architecture
        id: target-arch
        run: |
          echo "TARGET_ARCH=`rustc -vV | sed -n 's|host: ||p'`" >> "$GITHUB_OUTPUT"

      - name: Build Cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-cargo-${{ steps.target-arch.outputs.TARGET_ARCH }}-bookworm-rust:${{ inputs.rust-version }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup credentials
        run: |
          mkdir .rf
          echo "${{ secrets.configuration_base64 }}" | base64 --decode > .rf/configuration.test.json
          echo "${{ secrets.application_default_credentials_base64 }}" | base64 --decode > .rf/application_default_credentials.json
          
      - name: Run tests
        run: cargo test --all
